name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: "Hello World API Test\t"
      id: hello-world-api-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Hello World API Test\t"
        setup-command: "npm install\t"
        command: "npm test\t"
        timeout: 20
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HELLO-WORLD-API-TEST_RESULTS: "${{steps.hello-world-api-test.outputs.result}}"
      with:
        runners: hello-world-api-test
